services:
  back:
    container_name: back
    network_mode: "host"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - banco
    ports:
      - 8080:8080

  banco:
    container_name: banco
    image: mysql:8.0-debian
    environment:
      - MYSQL_DATABASE=APEX_I  
      - MYSQL_USER=apex_user
      - MYSQL_PASSWORD=senha123
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_ROOT_HOST="%"
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
